services:

  db:
    image: mongo:7.0.0
    container_name: db
    ports:
      - "4000:27017"
    restart: always

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
      - ./video-streaming/video:/usr/src/app/videos:z
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - NODE_ENV=development
    restart: "no"

  # azure-storage:
  #   image: azure-storage
  #   build:
  #     context: ./azure-storage
  #     dockerfile: Dockerfile-dev
  #   container_name: video-storage
  #   ports:
  #     - "4001:80"
  #   environment:
  #     - PORT=80
  #     - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
  #     - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
  #   restart: "no"

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - NODE_ENV=development
    restart: "no"
